# This is a remoteSwitch example configuration file for a multi purpose gpio
# switch, configured as a 8x2 bandswitch running on an Orange Pi Zero.

# Configuration for connection to the NATS broker
[nats]
broker-url = "localhost"
broker-port = 4222
username = ""
password = ""

# All remoteSwitches are at their core "switches". Here we specify the type
# and configuration key of the switch. In our case we select "multi_purpose_gpio".
[switch]
name = "w1mx"
type = "w1mx"
# type = "dummy_switch"
# type = "stackmatch_gpio"
# type = "ea4tx_remotebox"

# This is the main configuration key. The name of the key is arbitrary, however
# it must be referenced corectly in the [switch] key.
[w1mx]
name = "W1MX"
# setting index = 2 means that it will be visualized in the GUI after all other
# switches with an index < 2 and before all other switched with an index > 2.
index = 1
portname = "/dev/ttyP1AM"
radios = ["radio_a", "radio_b"]
terminals = ["10m", "15m", "20m", "40m", "80m", "160m", "Local"]
controls = ["rem_on", "tx_req", "ptt"]

[radio_a]
name = "A"
# index sets the order of this port for graphical representation in the GUI.
index = 0
enable_control = "tx_req"

# Second port for myBandswitch
[radio_b]
name = "B"
index = 1

[rem_on]
name = "Shutdown Radio"
channel = 1
[tx_req]
name = "TX Enabled"
channel = 2
[ptt]
name = "PTT"
channel = 3
